# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=140)),
                ('Fecha_inicio', models.DateTimeField()),
                ('Fecha_fin', models.DateTimeField()),
                ('Imagen', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
